class SampleTweetData

  # Created a representative sample of tweet texts as of Saturday, January 23rd middday EST.
  # This list tries to capture tweets that are targeted at tweak the tweet and not
  # random tweets that happen to have #haiti in them.

  TEXTS = [
    "#haiti pls use these data hashtags: #name [first last] #loc [address, intersection] #num [amount] #contact [@ or #]",
    "@ShaunKing #Haiti RT @internethaiti #trapped 6 #num 6 people ALIVE #loc Rue Du Centre PaP Building Napolitain #coor 18.544833,-72.342889",
    "#Haiti RT @internethaiti #trapped 6 #num 6 people ALIVE #loc Rue Du Centre PaP - Building Napolitain #coor 18.544833,-72.342889",
    "RT @Kenold UPDATE: WATER filtration transport 2 PaP OK, need 2 find final #loc in #Haiti. where is water most needed - Jacmel? pls RT",
    "#haiti #open #shelter 2 kid centers #loc San Jose Recovery & Good Sam Hosp, Jimani, DR border #src World Vision int'l",
    "#haiti #need med supplies: Lovenox, 4 autoclaves #loc Hop Sacré-Coeur Milot #status blog entry Jan 22",
    "#haiti pls tweet in format: #haiti #open [store/hospital/bank/etc] #loc [location] #date [day/time]",
    "RT @VRWCTexan #Haiti #open Hospital Sacre Coeur #loc Milot 904-223-7233 904-223-7233: full-svs 2ORs, trauma, ortho team waiting for patients",
    "RT @Meira_Davi: #Haiti Desperate need for #shelter: fam w/ kids in #loc Bon Repos, near LaPlaine. Rural area #hatiqua #redcross @conneally",
    "RT #haiti @InternetHaiti: RT @yveno76: #NEED food and water #loc BAUSSAN STREET #9 (500 people) Lat. 18.53416 Lon. -72.32425 via @Ushahidi",
    "RT @yveno76: Rescue need #name Caribbean SuperMkt #loc Delmas105 #info trappedfreezer section #src @amieemccaffrey Via ushahidi #Haiti",
    "URGENT: #Haiti Children in need of #water at #loc Delmas 103 #41 (Sebastien Cournoyer tried to specify loc) #hatiqua @conneally #redcross",
    "#Haiti Help needed for 3 people #loc Thomassin 32 Celin St. #food #water #supplies #hatiqua @conneally #redcross",
    "#Haiti 2 people desperately need #food #water #medical #help #Name :Ronald Cadet #loc in Foucha in Lelau St #50 in Bolosse. @conneally",
    "#Help needed in #loc Belosse betweeen 3rd and 4th ave Bolosse #Name Watson Telephone: 38489965 #hatiqua #redcross #haiti",
    "RT @CrisisCampMTL: @SpyDrMedia #Haiti 100 people in #need of #medical #help at #loc Church 337, Arcahaie Barbancourt. Telephone: 4693204",
    "@SpyDrMedia found this: #Haiti 100 people in #need of #medical #help at #loc Church 337, Arcahaie Barbancourt. Telephone: 4693204",
    "#Haiti RT 100 people in #need of #medical #help at #loc Church 337, Arcahaie Barbancourt. Telephone: 4693204",
    "RT @USAforHaiti: #Haiti #Need #food and water for 500 people #loc in Baussan Street #9 #date 22.01.10 #time 2:41pm EST #Helphaiti",
    "#Haiti #Helphaiti #loc SOPUDEP in Petion-Ville #Info still no doctors, supplies, housing #med #food #water #date 22.01.10 #time 2:50pm EST",
    "#Haiti #Need #food and water for 500 people #loc in Baussan Street #9 #date 22.01.10 #time 2:41pm EST #Helphaiti",
    "RT @QcprieQcprays: #LEADWITHVISION #Loc Doctors w/o Borders Medical Trtmt t Centers #Haiti http://www.m300ministri (cont) http://tl.gd/4q3pi",
    "#haiti pls tweet in format: #haiti #imok [name] #loc [location] #status [status] #contact [@ or #]",
    "RT @M300Ministries: #Haiti #Need food,h20,meds reports starving #Loc Latitude: 18.42775 / Longitude: -72.774162 Grand Goave #contact @yveno76 #rescuemehaiti",
    "RT @M300Ministries: #Haiti #need H20 #loc Latitude: 18.549999 / Longitude: -72.300003 terrain Monpellier village, at delmas 33.",
    "RT @M300Ministries: #Haiti #need food,h20 8 days no food #Loc Latitude: 18.986059 / Longitude: -72.292259 carfour debwos in the yard of the Acra",
    "#haiti #need crutches: Report from the field states that CRUTCHES are needed. Lots of amputees or injured in need. #src @firesideint",
    "@Beyaya #need #place #list of all #med teams wanting 2 help #Haiti, so #logistics can b #organized.#advise #crisiscommons #SOS",
    "@RAMhaiti URGENT #need: #WATER filtration system trying 2 get to #Haiti can you help? http://bit.ly/4PgbaY (via @kenold)",
    "@CrisisCampMTL: @SpyDrMedia #Haiti 100 people in #need of #medical #help at #loc Church 337, Arcahaie Barbancourt. Telephone: 4693204",
    "#haiti #offer hospital #Loc 75 miles from PaP #contact Tim 413-241-6526 or ttraynor1948@gmail.com",
    "@ISOHIMPACT RT #haiti #offer #17 nurses and doctors and medical supplies #need NGO #loc PA #poc @kristinebrite",
    "#haiti #offer - translations from Creole to English - @frantzone can help! Must spread info from Creole speakers! #con @frantzone",
    "#haiti use 1 main hashtag per twt: #imok, #ruok, #need, #offer or #have, #open [road, store or other], #close [road, store or other]",
    "RT @epiccolorado: #haiti #offer info Finnish #Redcross: plane arrived in PAP w/ complete surgical theatre + 100 bed post-op unit + 26 medics #src @conneally",
    "#haiti #offer info Map of Doctors Without Borders #med facilities in #Haiti http://bit.ly/7NJne5",
    "sophiabliu: #haiti #offering aggregated #info on Twitter users/lists, IMOK/RUOK, maps, Facebook, b.. http://bit.ly/4T1F4X via @YoTwits",
    "Map of food distributions centers in #haiti http://tinyurl.com/yhw2jxn #offering #loc",
    "RT @generation4him #Have 12 doctors 5 nurses creole translator, antibiotics and surgical supplies for #Haiti #source @generation4Him",
    "RT @epiccolorado: #haiti use 1 main hashtag per twt: #imok, #ruok, #need, #offer or #have, #open [road, store or other], #close [road, store or other]",
    "RT @epiccolorado: #haiti #date jan 19 WASH Cluster established 82 water / watsan distribution sites #have 180 water trucks for 180,000 people in #loc PaP",
    "RT @sophiabliu: #haiti CHF #have emergency kits for 1000 families include shelters, kitchen sets, mosquito nets, jerry cans, 4 large tens for hospital rooms",
    "RT @epiccolorado: we #have some water to share with #loc Bresma Orphanage, but need contact info. #Haiti #con @BHMhaiti Can anyone help?",
    "@USAforHaiti #Haiti Careca Breda Male-Port Au Prince #imok #>1deceased-crying thank You for reporting this.contact be processed",
    "@HaitiGoodNews #haiti #imok Ulrick Alexandre #src @sgtkjohn",
    "#Haiti #imok Bathelmy Augustin #info Adult Male wants family in Miami, FL to know he's alive - has water. #src @sgtkjohn",
    "RT @ungaro: #HAITI #RUOK: Domnq V. Lacombe seeks: Jacqs Joubert Goutier (CAMEP), Marianne Jsph VanEyll, Marie NicoleRose BastienCosyns, Antne Clerfond",
    "#HAITI #RUOK: Domnq V. Lacombe seeks: Jacqs Joubert Goutier (CAMEP), Marianne Jsph VanEyll, Marie NicoleRose BastienCosyns, Antne Clerfond",
    "RT @epiccolorado: #haiti #ruok looking for a woman in PaP Haiti named Dominique Balatier - anyone know how to find out if she's OK? #contact @marcusdonates",
    "@ShaunKing #Haiti RT @internethaiti #trapped 6 #num 6 people ALIVE #loc Rue Du Centre PaP Building Napolitain #coor 18.544833,-72.342889",
    "RT @ungaro: #HAITI #Trapped: @missinghaitians: Is Adolpho Prato still alive under rubble at Caribbean Market?? Not reunited w/ family Via @InternetHaiti",
    "RT @InternetHaiti: RT @ungaro: #HAITI #Trapped - MARTINE PIERRE PORTABLE (CELL Phone) = 38674702. Mesi",
    "RT @ungaro: #HAITI #TRAPPED: Rescue team desperate - Needs CELLPHONE Number MARTINE PIERRE to PINPOINT LOCATION at Universite Caraibe",
    "RT @ungaro: #HAITI #Trapped - MARTINE PIERRE PORTABLE (CELL Phone) = 38674702. Mesi (via @InternetHaiti)",
    "Treating #Haiti 's stream of #injured quake victims http://is.gd/6K0PR",
    "#haiti #open #shelter 2 kid centers #loc San Jose Recovery & Good Sam Hosp, Jimani, DR border #src World Vision int'l",
    "RT @VRWCTexan #Haiti #open Hospital Sacre Coeur #loc Milot 904-223-7233 904-223-7233: full-svs 2ORs, trauma, ortho team waiting for patients",
    "RT@yveno76:#open redcross mobile health clinics#loc Carrefour de Feuille, Croix deprez + Delmar 45 PaP #src @conneally 21 Jan 01.00pm #HAITI",
    "#Haiti. 2nd quake an hr ago. 6.0 magnitude. Little info available yet #closed Twitter server down."
  ].uniq

end
